### ISSUE TITLE
Crash when selecting "Contributors" in "About Squeak..." menu

### ISSUE THREAD

**Issue by c4f7fcce9cb06515** [hpi-swa/graalsqueak#93] opened 2019-12-13 12:50 UTC
GraalSqueak crashes when selecting "Contributors" in "About Squeak..." menu

GraalSqueak-1.0.0-rc6.image
graalvm-ce-java8-19.3.0
Kubuntu Linux 19.10

**Comment by fniephaus** [comment] 2019-12-13 13:46
Thanks for the bug report. I can reproduce the issue on macOS. GraalSqueak exists with the following error:
> ERROR: A Squeak/Smalltalk image cannot return a result, it can only exit.

So this looks like a control flow problem.

**Comment by fniephaus** [comment] 2019-12-13 16:16
A debugger is opened right before the crash:
![image](https://user-images.githubusercontent.com/2368856/70814667-394b6e00-1dcc-11ea-9e8d-76a7a974f748.png)

The root cause may therefore be something else...

**Comment by fniephaus** [comment] 2019-12-16 11:11
This will be fixed with the next release. Thanks again for the bug report!

**Closed by fniephaus** 2019-12-16 11:11 UTC
Labels: bug
